[package]
name = "pingasprite"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
image = "0.25.4"
serde = "1.0.210"
serde_derive = "1.0.210"
toml = "0.8.19"

[[bin]]
name = "pingasprite"
path = "source/code/main.rs"
