[io]
input_sprite_sheet_file_path = "assets/5944.png"
output_sprite_directory_path = "output/grounder"
output_sprite_format = "png"

[replacements]
000060ff = "00000000"
000030ff = "00000000"

# 1, 1
[[sprites]]
top = 500
left = 1
width = 80
height = 56

# 1, 2
[[sprites]]
top = 500
left = 82
width = 80
height = 56

# 1, 3
[[sprites]]
top = 500
left = 163
width = 80
height = 56

# 2, 1
[[sprites]]
top = 557
left = 1
width = 80
height = 56

# 2, 2
[[sprites]]
top = 557
left = 82
width = 80
height = 56

# 3, 1
[[sprites]]
top = 614
left = 1
width = 80
height = 56

# 3, 2
[[sprites]]
top = 614
left = 82
width = 80
height = 56

# 4, 1
[[sprites]]
top = 671
left = 1
width = 80
height = 56

# 4, 2
[[sprites]]
top = 671
left = 82
width = 80
height = 56