[io]
input_sprite_sheet_file_path = "assets/5944.png"
output_sprite_directory_path = "output/scratch"
output_sprite_format = "png"

[replacements]
000060ff = "00000000"

# 1, 1
[[sprites]]
top = 743
left = 1
width = 80
height = 56

# 1, 2
[[sprites]]
top = 743
left = 82
width = 80
height = 56

# 2, 1
[[sprites]]
top = 800
left = 1
width = 80
height = 56

# 2, 2
[[sprites]]
top = 800
left = 82
width = 80
height = 56

# 3, 1
[[sprites]]
top = 857
left = 1
width = 80
height = 56

# 3, 2
[[sprites]]
top = 857
left = 82
width = 80
height = 56

# 4, 1
[[sprites]]
top = 914
left = 1
width = 80
height = 56